// Generated by gencpp from file grace_attn_msgs/EmotionAttentionResult.msg
// DO NOT EDIT!


#ifndef GRACE_ATTN_MSGS_MESSAGE_EMOTIONATTENTIONRESULT_H
#define GRACE_ATTN_MSGS_MESSAGE_EMOTIONATTENTIONRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int64.h>
#include <std_msgs/Int64.h>
#include <sensor_msgs/Image.h>

namespace grace_attn_msgs
{
template <class ContainerAllocator>
struct EmotionAttentionResult_
{
  typedef EmotionAttentionResult_<ContainerAllocator> Type;

  EmotionAttentionResult_()
    : attention()
    , emotion()
    , visualization_frame()  {
    }
  EmotionAttentionResult_(const ContainerAllocator& _alloc)
    : attention(_alloc)
    , emotion(_alloc)
    , visualization_frame(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int64_<ContainerAllocator>  _attention_type;
  _attention_type attention;

   typedef  ::std_msgs::Int64_<ContainerAllocator>  _emotion_type;
  _emotion_type emotion;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _visualization_frame_type;
  _visualization_frame_type visualization_frame;





  typedef boost::shared_ptr< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> const> ConstPtr;

}; // struct EmotionAttentionResult_

typedef ::grace_attn_msgs::EmotionAttentionResult_<std::allocator<void> > EmotionAttentionResult;

typedef boost::shared_ptr< ::grace_attn_msgs::EmotionAttentionResult > EmotionAttentionResultPtr;
typedef boost::shared_ptr< ::grace_attn_msgs::EmotionAttentionResult const> EmotionAttentionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator1> & lhs, const ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator2> & rhs)
{
  return lhs.attention == rhs.attention &&
    lhs.emotion == rhs.emotion &&
    lhs.visualization_frame == rhs.visualization_frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator1> & lhs, const ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grace_attn_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb0f00a6f3b056b562935c8def10f302";
  }

  static const char* value(const ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb0f00a6f3b056b5ULL;
  static const uint64_t static_value2 = 0x62935c8def10f302ULL;
};

template<class ContainerAllocator>
struct DataType< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grace_attn_msgs/EmotionAttentionResult";
  }

  static const char* value(const ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int64 attention\n"
"std_msgs/Int64 emotion\n"
"sensor_msgs/Image visualization_frame\n"
"================================================================================\n"
"MSG: std_msgs/Int64\n"
"int64 data\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.attention);
      stream.next(m.emotion);
      stream.next(m.visualization_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmotionAttentionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grace_attn_msgs::EmotionAttentionResult_<ContainerAllocator>& v)
  {
    s << indent << "attention: ";
    s << std::endl;
    Printer< ::std_msgs::Int64_<ContainerAllocator> >::stream(s, indent + "  ", v.attention);
    s << indent << "emotion: ";
    s << std::endl;
    Printer< ::std_msgs::Int64_<ContainerAllocator> >::stream(s, indent + "  ", v.emotion);
    s << indent << "visualization_frame: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.visualization_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRACE_ATTN_MSGS_MESSAGE_EMOTIONATTENTIONRESULT_H
